# Vectors

## Inner Product -- Dot Product

$ a = \begin{bmatrix}
a_1 & a_2 & ... & a_n
\end{bmatrix}, b = \begin{bmatrix}
b_1 \\ b_2 \\ ... \\ b_n
\end{bmatrix} $

Expressing the above example in this way, a 1 × 3 matrix (row vector) is multiplied by a 3 × 1 matrix (column vector) to get a 1 × 1 matrix that is identified with its unique entry:

`[ 1 , 3 , − 5 ] ⋅ [ 4 , − 2 , − 1 ] = ( 1 × 4 ) + ( 3 × − 2 ) + ( − 5 × − 1 ) = 4 − 6 + 5 = 3`

$a \cdot b = $

$\begin{bmatrix} 1 & 3  & −5 \end{bmatrix} \cdot \begin{bmatrix} 4 \\ −2 \\ −1 \end{bmatrix} = 3 $

## Outer Product -- Tensor Product

$$
\mathbf{v}=\left[\begin{array}{c}
v_{1} \\
v_{2} \\
\vdots \\
v_{n}
\end{array}\right], \mathbf{w}=\left[\begin{array}{c}
w_{1} \\
w_{2} \\
\vdots \\
w_{m}
\end{array}\right]
$$

Tensor product of $\mathbf{v}$ and $\mathbf{w}$ is given by

$$
\underset{\underset{\scriptstyle\text{\bigotimes}}{\scriptstyle}}{\mathbf{v} \bigotimes \mathbf{w}} = 
\underset{\underset{\scriptstyle\text{\otimes}}{\scriptstyle}}{\mathbf{v} \otimes \mathbf{w}}=\left[\begin{array}{cccc}
v_{1} w_{1} & v_{1} w_{2} & \cdots & v_{1} w_{m} \\
v_{2} w_{1} & v_{2} w_{2} & \cdots & v_{2} w_{m} \\
\vdots & \vdots & \ddots & \vdots \\
v_{n} w_{1} & v_{n} w_{2} & \cdots & v_{n} w_{m}
\end{array}\right]
$$

https://www.math-linux.com/latex-26/faq/latex-faq/article/latex-tensor-product

The outer product $v \otimes w$ is equivalent to a matrix multiplication $vw^\top$.

# __Matrices__

# Basics

A matrix is described as having M rows and N columns. When given the shape of a matrix, the number of rows comes first, and the number of columns comes second. _Example:_ This is a 2x3 matrix. M = 2 and N = 3.

$ \begin{bmatrix}
-5 & 0 & 2 \\ 
 4 & 3 & 0
\end{bmatrix} $

# Matrix Multiplication

## Dot Product

When multiplying two matrices, the dimensions of the first matrix are denoted by MxN, and the dimensions of the second matrix are denoted by NxP. To perform multiplication, the Ns must be equal. The result is an MxP matrix. https://www.mathsisfun.com/algebra/matrix-multiplying.html

To perform the dot product, multiply the numbers in each row of Matrix \#1 by the corresponding numbers in each column of Matrix \#2. Sum over the products.  

$ \begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6
\end{bmatrix} \cdot \begin{bmatrix}
7 & 8 \\ 
9 & 10 \\
11 & 12
\end{bmatrix}$

Row \#1 * Column \#1: $(1, 2, 3) \cdot (7, 9, 11) = 1×7 + 2×9 + 3×11 = 58$<br>
Row \#1 * Column \#2: $(1, 2, 3) \cdot (8, 10, 12) = 1 \times 8 + 2 \times 10 + 3 \times 12 = 64$<br>
Row \#2 * Column \#1: $(4, 5, 6) \cdot (7, 9, 11) = 4×7 + 5×9 + 6×11 = 139$<br>
Row \#2 * Column \#2: $(4, 5, 6) \cdot (8, 10, 12) = 4×8 + 5×10 + 6×12 = 154$<br>

$ \begin{bmatrix}
58 & 64 \\ 
139 & 154
\end{bmatrix}$

## Matrix by Column Vector Multiplication

Multiplication of a matrix by a column vector is a special case of matrix-by-matrix multiplication. The column vector can be treated as a Nx1 matrix.

$ \begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6
\end{bmatrix} \cdot \begin{bmatrix}
7 \\ 
9 \\
11
\end{bmatrix}$

Row \#1 * Column \#1: $(1, 2, 3) \cdot (7, 9, 11) = 1×7 + 2×9 + 3×11 = 58$<br>
Row \#2 * Column \#1: $(4, 5, 6) \cdot (7, 9, 11) = 4×7 + 5×9 + 6×11 = 139$<br>

$ \begin{bmatrix}
58 \\ 
139 
\end{bmatrix}$

# Eigenvalues and Eigenvectors

https://www.youtube.com/watch?v=PFDu9oVAE-g&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=14

An eigenvector is a vector that is not thrown of its span (line containing it) during the linear transformation specified by a matrix. The vector can be stretched or squished, but that is all. The eigenvalue is the scalar that represents stretching or squishing. 

<font size=5>
$A$ = matrix<br>
$\vec{v}$ = vector<br>
$\lambda$ = eigenvalue
</font>

## Formula
<br>
<font size=5>
    $A\vec{v} = \lambda\vec{v}$
    </font>
    
Notice that $A$ is a matrix and $\lambda$ is a scalar. We need to express the scalar as a matrix so we can do algebra.

Scalar $\lambda$ is equivalent to a matrix with $\lambda$ down the diagonal and zeros everywhere else. Suppose $A$ is a 3x3 matrix, then $\lambda$ = 

$ \begin{bmatrix}
\lambda & 0 & 0 \\ 
0 & \lambda & 0 \\
0 & 0 & \lambda
\end{bmatrix}$

That matrix is simply $\lambda$ times the identity matrix $\lambda I$. So, it is possible to factor the matrix like this:

$ \lambda * \begin{bmatrix}
1 & 0 & 0 \\ 
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}$

Thus we have.

<br>
<font size=5>
    $A\vec{v} - (\lambda I)\vec{v} = \vec{0}$ <br>
    $(A - \lambda I) \vec{v} = \vec{0}$
    </font>

This form featues matrix-vector multiplication on both sides.


Suppose $A$ looks like this:

$ \begin{bmatrix}
3 & 1 & 4 \\ 
1 & 5 & 9 \\
2 & 6 & 5
\end{bmatrix}$

Subtracting $\lambda I$ gives us

$ \begin{bmatrix}
3-\lambda & 1 & 4 \\ 
1 & 5-\lambda & 9 \\
2 & 6 & 5-\lambda
\end{bmatrix}$


The only way we can have an eigenvector is if the determinant = 0.

Determinants are easier to calculate with a 2x2 matrix. Suppose $A - \lambda I$ looks like this:

$ \begin{bmatrix}
3 & 1 \\ 
0 & 2
\end{bmatrix}$

We compute the eigenvalue by computing the determinant and solving where it equals 0.

$ det(\begin{bmatrix}
3-\lambda & 1 \\ 
0 & 2-\lambda
\end{bmatrix}) = (3 - \lambda)(2 - \lambda) = 0$

$\lambda = 2, 3$

To get the eigenvector, plug in $\lambda$ into the matrix and solve for the vector. Example where $\lambda = 2$.

$ \begin{bmatrix}
3-2 & 1 \\ 
0 & 2-2
\end{bmatrix}\begin{bmatrix}
x \\
y
\end{bmatrix} = \begin{bmatrix}
0 \\
0
\end{bmatrix}$

Solve as a system of equations.

$1x + 1y = 0$<br>
$0x + 0y = 0$

$x = -y$

Thus, the vectors are infinitely many eigenvector solutions.


## Diagonal Matrix

Given a diagonal matrix, where there are non-zeros down the diagonal and zeros everywhere else. Each basis vector (column vector) is an eigenvector.



# Eigendecomposition

https://www.youtube.com/watch?v=oshZQtYAh84

* Maximum of f(x) = largest eigenvalue
* Minimum of f(x) = smallest eigenvalue

<br><br>

<font size =4>
$A$ = a matrix <br>
    
$\Lambda$ = the second decomposed matrix. <br>
  * $\Sigma$ is 
    
$V^\top$ = the third decomposed matrix. <br>
  * $V^\top$ is an orthogonal matrix.
   
    </font>

## Formulas

<br><br>
<font size=4>
$A = (V\Lambda V^{-1})$
</font>

First we calculate $A$ and $A^\top$
<br><br>
<font size=4>
$A^\top A = (V\Sigma^\top U^\top) U\Sigma V^\top$
</font>

First we calculate $A$ and $A^\top$
<br><br>
<font size=4>
$A^\top A = (V\Sigma^\top U^\top) U\Sigma V^\top$
</font>

First we calculate $A$ and $A^\top$
<br><br>
<font size=4>
$A^\top A = (V\Sigma^\top U^\top) U\Sigma V^\top$
</font>

# Single Value Decomposition

We are looking for vectors that start out orthoganal and remain orthogonal after transformation by a matrix. 


https://www.youtube.com/watch?v=mBcLRGuAFUk
<br><br>

<font size =4>
$A$ = a matrix <br>
        
$U$ = the first decomposed matrix.<br>
* $U$ is an orthogonal matrix.
    
$\Sigma$ = the second decomposed matrix. <br>
  * $\Sigma$ is a diagonal matrix.
    
$V^\top$ = the third decomposed matrix. <br>
  * $V^\top$ is an orthogonal matrix.
   
    </font>


## Formulas

We start with the given formula
<br><br>
<font size=4>
$A = U \Sigma V^\top$ <br>
</font>

First we calculate $A$ and $A^\top$
<br><br>
<font size=4>
$A^\top A = (V\Sigma^\top U^\top) U\Sigma V^\top$
</font>

Since $U$ is orthogonal, $U^\top U$ is the identiy matrix, which cancels the $U$ terms. That gives us
<br><br>
<font size=4>
$= V (\Sigma^\top \Sigma) V^\top$
</font>

$\Sigma^\top \Sigma$ is a diagonal matrix.

For $A^\top A$, the eigenvalues are in $\Sigma^\top \Sigma$ and the eigenvectors are in $V$. The eigenvectors in $V$ are orthogonal, and the eigenvalues in $\Sigma^\top \Sigma$ are positive.

$\lambda$ for $A^\top A$ is $\sigma^2$ for $A$.



Now we calculate $AA^\top$.
<br><br>
<font size=4>
$AA^\top = U \Sigma V^\top V \Sigma^\top U^\top$    
</font>

$V$ is an orthogonal matrix, and $V^\top V$ is the identiy matrix, which cancels the $V$ terms. 

Now we know that $U$ is the eigenvector matrix for $AA^\top$. $\Sigma^\top \Sigma$ contains the eigenvalues.

## Example

$A = \begin{bmatrix}
2 & 2 \\ 
1 & 1
\end{bmatrix}$

Notice that this is a singular matrix. Its determinant is 0. Row 1 is a scalar product of row 2.


Professor Strang gives the solution as 

$A = U \Sigma V^\top$

$A = \begin{bmatrix}
2 & 2 \\ 
1 & 1
\end{bmatrix} = 
\frac{\begin{bmatrix}
2 & 1 \\ 
-1 & 2
\end{bmatrix}}{\sqrt{5}}
\begin{bmatrix}
\sqrt{10} & 0 \\ 
0 & 0
\end{bmatrix}
\frac{\begin{bmatrix}
1 & 1 \\ 
1 & -1
\end{bmatrix}}{\sqrt{2}}$

I believe there are additional solutions because there are multiple eigenvectors of $AA^\top$. I observed that the additional solutions I found differ only by the sign of some elements of the each matrix. 

https://www.emathhelp.net/calculators/linear-algebra/svd-calculator/?i=%5B%5B2%2C2%5D%2C%5B1%2C1%5D%5D

## U

$AA^\top = 
\begin{bmatrix}
8 & 4 \\ 
4 & 2
\end{bmatrix}
$ <br><br>
Eigenvalue: $10$, eigenvector $\begin{bmatrix}
2  \\ 
1 
\end{bmatrix}
$<br><br>
Eigenvalue: $0$, eigenvector $\begin{bmatrix}
-\frac{1}{2}  \\ 
1 
\end{bmatrix}$

Non-normalized matrix: $\begin{bmatrix}
2 & -\frac{1}{2} \\ 
1 & 1
\end{bmatrix}$

Normalize by calculating the unit vector of the column 0 vector. Magnitude of vector $[2, 1] = \sqrt{2^2 + 1^2} = \sqrt{5}$.

Normalized matrix: $\begin{bmatrix}
\frac{2}{\sqrt{5}} & -\frac{1}{\sqrt{5}} \\ 
\frac{1}{\sqrt{5}} & \frac{2}{\sqrt{5}}
\end{bmatrix} = \begin{bmatrix}
0.894 & -0.447 \\ 
0.447 & 0.894
\end{bmatrix}$

This is the same as Professor Strang's solution for U, except that the minus sign was moved from lower-left to upper-right.

## $\Sigma$

$AA^\top = 
\begin{bmatrix}
8 & 4 \\ 
4 & 2
\end{bmatrix}
$ <br><br>

Since $\Sigma \Sigma^\top$ contains the eigenvalues. To find the eigenvalues of $A$, take the square root of each eigenvalue and put them in a diagonal matrix. 

Eigenvalues of $AA^\top = [10, 0]$

Eigenvalues of $A = [\sqrt{10}, 0]$

$\Sigma=\begin{bmatrix}
\sqrt{10} & 0 \\ 
0 & 0
\end{bmatrix}$

## V

An alternative to the following technique is to compute $A^\top A$ and solve for $V$ the same way we solved for $U$.
<br><br>
<font size=4>
$v_i = \frac{1}{\sigma_i} * A^\top * u_i$
    
<br>
$v_1 = \frac{1}{\sigma_i} * \begin{bmatrix}
2 & 2 \\ 
1 & 1
\end{bmatrix}^\top * u_1$
    
$= \frac{1}{\sqrt{10}} * \begin{bmatrix}
2 & 1 \\ 
2 & 1
\end{bmatrix} * \begin{bmatrix}
\frac{2}{\sqrt{5}} \\ 
\frac{1}{\sqrt{5}}
\end{bmatrix}$
    
$= \begin{bmatrix}
\frac{\sqrt{2}}{2} \\ 
\frac{\sqrt{2}}{2}
\end{bmatrix}$
    
Since we have run out of nonzero $\sigma_i$ and need one more vector, find the orthogonal vector to all the found vectors by finding the null space of the matrix whose rows are the found vectors: 
    
$= \begin{bmatrix}
-1 \\ 
1
\end{bmatrix}$
    
Normalize the vector to:
    
$\begin{bmatrix}
-\frac{\sqrt{2}}{2} \\ 
\frac{\sqrt{2}}{2}
\end{bmatrix}$    
    
$ V = \begin{bmatrix}
\frac{\sqrt{2}}{2} & -\frac{\sqrt{2}}{2} \\ 
\frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2}
\end{bmatrix} = \begin{bmatrix}
0.707 & -0.707 \\ 
0.707 & 0.707
\end{bmatrix}$
    
</font>

## Python SVD Directly

In [78]:
import numpy as np
a = np.array([[2, 2], [1, 1]])
print(a)

[[2 2]
 [1 1]]


In [79]:
u, s, vh = np.linalg.svd(a, full_matrices=True)

In [80]:
print(u)
print(u * (5**.5))

[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
[[-2. -1.]
 [-1.  2.]]


In [81]:
s = np.diag(s)
print(s)
print(s * np.sqrt(10))

[[3.16227766 0.        ]
 [0.         0.        ]]
[[10.  0.]
 [ 0.  0.]]


In [82]:
print(vh)
print(vh * (2**.5))

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[[-1. -1.]
 [-1.  1.]]


## Python SVD fro Eigenvectors

In [86]:
# create simple 3x3 matrix
A = np.array([[2, 2], [1, 1]])
At = np.transpose(A)
AtA = At @ A
AAt = A @ At

#print(AAt)

# get eigenvalues and eigenvectors
values, vectors = np.linalg.eig(AAt) # U
values2, vectors2 = np.linalg.eig(AtA) # V

values = np.sqrt(np.diag(values))
print("Sigma\n", values)
print("U\n", vectors)
print("V\n", vectors2)


Sigma
 [[3.16227766 0.        ]
 [0.         0.        ]]
U
 [[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]
V
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [87]:
# Prove that this is a valid solution by recombining the matrices
vectors @ values @ np.transpose(vectors2)

array([[2., 2.],
       [1., 1.]])

# Operators

## Python Operators

`*` = element-wise product.<p>
`**2` = element-wise square.<p>
`np.dot` = dot product.

    
## Math Operators

$A^{\top}$ = Transpose of $A$. <p>
$AB$ or $A \cdot B$ = Dot product of $A$ and $B$.<p>
$A \times B$ = Cross product of $A$ and $B$.  <p>
$A * B$ = Convolution on input image $A$ and filter $B$. <p>
$||A||_2$ = Frobenius norm.

# Application to Logistic Regression

## Lazy Programmer

The Logistic Regression course by Lazy Programmer Inc. at https://www.udemy.com/course/data-science-logistic-regression-in-python/ uses notation including a N samples x D features input matrix.

### Notation from Logistic Regression Notebook
$N = Number \ of \ samples $ <br>
$D = Number \ of \ dimensions \ (features) $ <br>
$\textbf{X} = N\ x\ D\  matrix $ <br>
$\textbf{w} = N\ x\ 1\  matrix \ of \ weights $ <br>
$h(x) = hypothesis \ function $ <br>
$z = \textbf{w}^{\textbf{T}}\textbf{x}$ <br>

In [1]:
import numpy as np

In [2]:
X = np.matrix([[1,2,3],[3,2,1],[3,3,3],[4,4,4],[5,4,3]])
print('X')
print(X)
# print('shape = {}, N = {} D = {}'.format(X.shape), X.shape[0], X.shape[1])
print('shape = {}, N = {} D = {}'.format(X.shape, X.shape[0], X.shape[1]))
print()
w = np.matrix([[10], [9], [8], [7], [6]])
print('w.T')
print(w.T)
print('shape = {}, N = {} D = {}'.format(w.T.shape, w.T.shape[0], w.T.shape[1]))
print()

product = w.T.dot(X)
print('Product')
print(product)
print('shape = {}, N = {} D = {}'.format(product.shape, product.shape[0], product.shape[1]))
print()
# print(X*w)

X
[[1 2 3]
 [3 2 1]
 [3 3 3]
 [4 4 4]
 [5 4 3]]
shape = (5, 3), N = 5 D = 3

w.T
[[10  9  8  7  6]]
shape = (1, 5), N = 1 D = 5

Product
[[119 114 109]]
shape = (1, 3), N = 1 D = 3



## Professor Andrew Ng (Stanford)
The deep learning course by Andrew Ng uses an `n`x`m` input matrix.

$m =$ number of examples in the dataset.<br>
$n_{x} =$ input size <br>
$n_{y} =$ output size <br>
$X \in \mathbb{R}^{n_x \ x \ m} $ = is the input matrix  <br>
$x^{(i)} \in \mathbb{R}^{n_x}$ = the i<sup>th</sup> example represented as a column vector.

## Several Techniques to Multiply

Several methods are available to multiply numpy matrices.

In [21]:
product = np.dot(w.T, X)
print('Product')
print(product)

Product
[[119 114 109]]


In [22]:
print('Product')
print(w.T*X)

Product
[[119 114 109]]


In [23]:
print('Product')
print(w.T.dot(X))

Product
[[119 114 109]]


# Warnings about Matrices in Python

## Rank-1 Array
An array with a shape like (5,) does not behave consistently as a row vector or a column vector. The solution is to declare a 1x5 or 5x1 matrix. A 5x1 is a colum vector. A 1x5 is a row vector.

In [24]:
import numpy as np

a = np.random.randn(5)

In [25]:
print(a.shape)

(5,)


In [26]:
print(a.T.shape)

(5,)


In [27]:
print(np.dot(a,a.T))

3.915311471066201


In [28]:
a = np.random.randn(5,1)
print(a)

[[-1.12373755]
 [ 1.27613696]
 [-0.23290096]
 [ 1.17966469]
 [ 1.42182608]]


In [29]:
print(a.T)

[[-1.12373755  1.27613696 -0.23290096  1.17966469  1.42182608]]


In [30]:
print(np.dot(a, a.T))

[[ 1.26278608 -1.43404302  0.26171955 -1.32563351 -1.59775935]
 [-1.43404302  1.62852554 -0.29721352  1.50541371  1.81444481]
 [ 0.26171955 -0.29721352  0.05424286 -0.27474504 -0.33114466]
 [-1.32563351  1.50541371 -0.27474504  1.39160877  1.67727801]
 [-1.59775935  1.81444481 -0.33114466  1.67727801  2.02158939]]


In [34]:
# It is possible to reshae a rank-1 array to a matrix.
b = np.random.randn(5)
print("Rank-1 Array")
print(b)
print("Shape")
print(b.shape)
print()
b = b.reshape([5,1])
print("Matrix")
print(b)
print("Shape")
print(b.shape)

Rank-1 Array
[ 0.10233763  0.10351315 -1.92455824 -1.23169823 -0.36765966]
Shape
(5,)

Matrix
[[ 0.10233763]
 [ 0.10351315]
 [-1.92455824]
 [-1.23169823]
 [-0.36765966]]
Shape
(5, 1)


# Frobenius Norm

1. Take the element-wise square of matrix `A`.
1. Sum over the elements of resulting matrix `A**2`. This yields a scalar.
1. Take the square root of the result.

## Formula

<font size=5>
$\left \| A \right \|_{F} = \left \| A \right \|_{2}$<p>
    $= \sqrt{\sum_{i} \sum_{j}|a_{ij}|^2}$

## Example

$A = \begin{bmatrix}
2 & -2 & 1\\ 
-1 & 3  & -1\\
2 & -4 & 1
\end{bmatrix}$<p>
    $= \sqrt{( |2|^2 + |-2|^2 + |1|^2 + |-1|^2 + |3|^2 + |-1|^2 + |2|^2 + |-4|^2 + |1|^2 }$<p>
    $= \sqrt{(41)} \approx 6,40 $
    
https://s-mat-pcs.oulu.fi/~mpa/matreng/eem5_1-1.htm

## Numpy

In [13]:
import numpy as np
from numpy import linalg as LA

In [14]:
A = np.array([2, -2, 1, -1, 3, -1, 2, -4, 1])
A

array([ 2, -2,  1, -1,  3, -1,  2, -4,  1])

In [15]:
B = a.reshape((3, 3))
B

array([[ 2, -2,  1],
       [-1,  3, -1],
       [ 2, -4,  1]])

In [21]:
LA.norm(B, ord='fro')

6.4031242374328485

## Numpy without `linalg`

In [17]:
B_squared = B ** 2
B_squared

array([[ 4,  4,  1],
       [ 1,  9,  1],
       [ 4, 16,  1]], dtype=int32)

In [19]:
B_sum = np.sum(B_squared)
B_sum

41

In [20]:
B_F = np.sqrt(B_sum)
B_F

6.4031242374328485

# 1-Norm

The 1-norm is the maximum of the column sums.

## Formula
<p>
<font size=5>
$\left \| A \right \|_{1} = max_{1 \le j \le n} \sum_{i=1}^{m}|a_{ij}|$
    </font>

## Example

 $max[ |2| + |-1| + |2|, |-2| + |3| + |-4|, |1| + |-1| + |2| ] = max[ 5, 9, 4 ] = 9$

## Numpy

In [22]:
LA.norm(B, ord=1)

9.0

# $\infty$-Norm

This norm is the maximum of the row sums.

## Formula
<p>
<font size=5>
$\left \| A \right \|_{\infty} = max_{1 \le i \le m} \sum_{j=1}^{n}|a_{ij}|$
    </font>

## Example

$= max[ |2| + |-2| + |1|, |-1| + |3| + |-1|, |2| + |-4| + |1| ] = max[ 5, 5, 7 ] = 7$

## Numpy

In [26]:
LA.norm(B, ord=np.inf)

7.0

# Convolutions

The discrete convolution operation is defined as

$(a * v)[n] = \sum_{m = -\infty}^{\infty} a[m] v[n - m]$



from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dropout 
from tensorflow.keras.layers import Conv2DTranspose