## Introduction to Logistic Regression

### Standard Form of a Line

$$0 = ax + by + c$$

### Hypothesis function

$$h(x,y) = a \ function \ in \ x \ and \ y$$

### Conversion to Vectors

$$(x, y) \rightarrow (x_{1}, x_{2}) = \textbf{x}$$

Constants in the linear equation are renamed to $w_{i}$. The bias term, or intercept is $w_{0}$. Vector $\textbf{x}$ is a vector of weights.

$$h(\textbf{x}) = \textbf{w}^{\textbf{T}}\textbf{x}$$

## Logistic Function

### Notation
$N = Number \ of \ samples $ <br>
$D = Number \ of \ dimensions \ (features) $ <br>
$\textbf{X} = N\ x\ D\  matrix $ <br>
$\textbf{w} = N\ x\ 1\  matrix \ of \ weights $ <br>
$h(x) = hypothesis \ function $ <br>
$z = \textbf{w}^{\textbf{T}}\textbf{x}$ <b><i>This may be wrong. It probably should be</i></b><br>
$z = \textbf{x}\cdot\textbf{w} \ or \ \textbf{x}\textbf{w}^{\textbf{T}}$<br>


https://en.wikipedia.org/wiki/Logistic_function

In logistic regression, this is referred to as the sigmoid.

$$\sigma (z) = \frac{1}{1 + e^{-z}}$$

### Logistic Function in Vector Form

$$P(y = 1 \ | \ x) = \sigma (w^{T}x)$$

### Basic Example of Logistic Regression

In [50]:
import numpy as np

N = 100
D = 2

# Generate NxD matrix with random values.
# randn pulls random numbers from the normal distribution 
# with mean = 0 and variance = 1
X = np.random.randn(N,D)
print(type(X))
print(X)



<class 'numpy.ndarray'>
[[ -1.78249292e+00   5.22138548e-01]
 [  6.93370899e-01   2.94768653e-01]
 [  1.56848794e+00  -4.79774023e-01]
 [  3.92686668e-01  -1.42968464e-01]
 [  5.59379448e-01   7.73621179e-01]
 [ -5.41082310e-01   8.11199045e-01]
 [  2.85954190e-01  -1.88380560e-02]
 [  1.62963201e-01   2.89099384e-01]
 [  1.29333643e+00  -7.08713605e-01]
 [ -5.68361664e-01  -2.14180002e-01]
 [ -5.80372972e-01  -2.71225885e-03]
 [ -1.44326207e+00  -6.65855516e-01]
 [  4.31067153e-01   1.28066365e+00]
 [  1.29304437e+00   5.23389675e-01]
 [ -1.72291672e+00   9.10439567e-01]
 [  8.33939537e-01   1.68599278e+00]
 [ -1.70622143e+00   2.20362947e-01]
 [  1.05973181e-01   2.39906146e-01]
 [ -2.22902024e+00  -6.26782631e-01]
 [ -1.15444293e+00  -1.94711838e-01]
 [ -2.80699154e+00   3.87932546e-01]
 [ -2.24333060e+00  -2.35100354e-01]
 [  7.68074500e-01   2.09120598e+00]
 [  6.68764193e-01  -6.52384279e-01]
 [ -1.11907008e+00  -1.88963737e-01]
 [  4.19353359e-02  -8.18256615e-01]
 [ -1.61828695

In [51]:
#Add a bias term by
#(1) Add a column on 1s in the original data.
#(2) Include the bias in the weights w[0]

# Transpose a 1xN matrix to get an Nx1 matrix
ones = np.array([[1]*N]).T
print(ones)


[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [52]:
#Concatenate the vector of 1s to the original dataset to make vector Xb
Xb = np.concatenate((ones, X), axis = 1)
print(Xb)

[[  1.00000000e+00  -1.78249292e+00   5.22138548e-01]
 [  1.00000000e+00   6.93370899e-01   2.94768653e-01]
 [  1.00000000e+00   1.56848794e+00  -4.79774023e-01]
 [  1.00000000e+00   3.92686668e-01  -1.42968464e-01]
 [  1.00000000e+00   5.59379448e-01   7.73621179e-01]
 [  1.00000000e+00  -5.41082310e-01   8.11199045e-01]
 [  1.00000000e+00   2.85954190e-01  -1.88380560e-02]
 [  1.00000000e+00   1.62963201e-01   2.89099384e-01]
 [  1.00000000e+00   1.29333643e+00  -7.08713605e-01]
 [  1.00000000e+00  -5.68361664e-01  -2.14180002e-01]
 [  1.00000000e+00  -5.80372972e-01  -2.71225885e-03]
 [  1.00000000e+00  -1.44326207e+00  -6.65855516e-01]
 [  1.00000000e+00   4.31067153e-01   1.28066365e+00]
 [  1.00000000e+00   1.29304437e+00   5.23389675e-01]
 [  1.00000000e+00  -1.72291672e+00   9.10439567e-01]
 [  1.00000000e+00   8.33939537e-01   1.68599278e+00]
 [  1.00000000e+00  -1.70622143e+00   2.20362947e-01]
 [  1.00000000e+00   1.05973181e-01   2.39906146e-01]
 [  1.00000000e+00  -2.22902

In [53]:
#Randomly initialize a weight vector
w = np.random.randn(D + 1)
print(w)
# One-dimensional row vector.

[-1.28446505  0.20895383 -0.4426675 ]


In [54]:
# ASIDE:
# How to transpose convert a row vector to a
# 2-dimensional 1xD array and 
# transpose it to a 2-dimensional Nx1 array.
w2 = w[np.newaxis]
print(w2.T)

[[-1.28446505]
 [ 0.20895383]
 [-0.4426675 ]]


In [55]:
# ASIDE:
# Multiplication of 100x3 and 3x1 arrays using "@",
# which was introduced in Python 3.5 and refers to the 
# matmul function.
print(w2.shape)
print(Xb.shape)
z2 = Xb @ w2.T

# Transpose 100x1 array to 1x100 array.
print(z2.T)

(1, 3)
(100, 3)
[[-1.88805754 -1.27006705 -0.74434312 -1.13912418 -1.51003753 -1.75661773
  -1.21637483 -1.37838817 -0.70049297 -1.30841587 -1.40453558 -1.29128759
  -1.7613001  -1.24596608 -2.04749711 -1.8565444  -1.73853407 -1.3685202
  -1.47277107 -1.43949772 -2.04272182 -1.64914629 -2.04968187 -0.85593489
  -1.43465093 -0.91348689 -1.01276211 -1.07889539 -1.42923608 -2.01802553
  -1.4190677  -1.38102087 -0.42740013 -0.66401167 -0.87775218 -1.07707796
  -1.20160388 -1.57348373 -1.68113948 -1.65586638 -1.24994284 -1.48503898
  -1.21359588 -1.38822585 -1.09386226 -1.34774004 -1.27312954 -0.73255701
  -1.11071949 -0.94397452 -1.26566783 -1.36790255 -1.59296042 -1.04839743
  -1.10971441 -2.09089113 -0.93020996 -1.56368218 -1.46483501 -1.3880812
  -1.60755724 -1.73610945 -1.23124126 -1.17838983 -1.3494294  -1.08361127
  -0.85187427 -1.75339401 -1.44719656 -0.79333346 -1.35477057 -0.8840284
  -1.85496164 -1.14039063 -0.59460283 -0.96209684 -1.25046792 -1.86732225
  -1.66327654 -1.56018404

In [56]:
#Calculate the dot product between each row of X and w
z = Xb.dot(w)
print(z)

[-1.88805754 -1.27006705 -0.74434312 -1.13912418 -1.51003753 -1.75661773
 -1.21637483 -1.37838817 -0.70049297 -1.30841587 -1.40453558 -1.29128759
 -1.7613001  -1.24596608 -2.04749711 -1.8565444  -1.73853407 -1.3685202
 -1.47277107 -1.43949772 -2.04272182 -1.64914629 -2.04968187 -0.85593489
 -1.43465093 -0.91348689 -1.01276211 -1.07889539 -1.42923608 -2.01802553
 -1.4190677  -1.38102087 -0.42740013 -0.66401167 -0.87775218 -1.07707796
 -1.20160388 -1.57348373 -1.68113948 -1.65586638 -1.24994284 -1.48503898
 -1.21359588 -1.38822585 -1.09386226 -1.34774004 -1.27312954 -0.73255701
 -1.11071949 -0.94397452 -1.26566783 -1.36790255 -1.59296042 -1.04839743
 -1.10971441 -2.09089113 -0.93020996 -1.56368218 -1.46483501 -1.3880812
 -1.60755724 -1.73610945 -1.23124126 -1.17838983 -1.3494294  -1.08361127
 -0.85187427 -1.75339401 -1.44719656 -0.79333346 -1.35477057 -0.8840284
 -1.85496164 -1.14039063 -0.59460283 -0.96209684 -1.25046792 -1.86732225
 -1.66327654 -1.56018404 -1.82867988 -1.93180128 -0.77

In [57]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [58]:
# Results are Nx1
print(sigmoid(z))

[ 0.13146611  0.21924577  0.32205515  0.2424812   0.18093323  0.14721445
  0.22857504  0.20126799  0.33170294  0.21275205  0.19709737  0.21563495
  0.14662759  0.22339921  0.11430553  0.13510634  0.14949923  0.20285903
  0.18652179  0.19162314  0.11478987  0.16122436  0.11408453  0.29818936
  0.19237505  0.28628684  0.26643965  0.25371511  0.19321774  0.11732331
  0.19480778  0.20084509  0.39474733  0.33983902  0.2936438   0.25405938
  0.23119002  0.17172032  0.15694464  0.16031767  0.22271003  0.18466752
  0.22906542  0.19969114  0.25089169  0.20624009  0.218722    0.32463386
  0.24773678  0.28009821  0.21999975  0.20295893  0.16896779  0.25953296
  0.24792414  0.10998531  0.28288212  0.17311891  0.18772894  0.19971426
  0.16692803  0.14980778  0.22596425  0.23534183  0.20596367  0.25282323
  0.29903984  0.14761963  0.19043339  0.31145336  0.20509154  0.29234369
  0.1352914   0.24224865  0.35557945  0.27645857  0.22261915  0.13385186
  0.15932265  0.17362024  0.13839561  0.12655134  0

## Matrix Multiplication

### Option 1: Declare Objects as np.matrix

In [59]:
A = np.matrix([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
print(A)
print(A.shape)
B = np.matrix([[2],[3],[4]])
print(B)
print(B.shape)
print(A*B)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
(5, 3)
[[2]
 [3]
 [4]]
(3, 1)
[[ 9]
 [18]
 [27]
 [36]
 [45]]


### Option 2: Use the @ Operator

In [60]:
E = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
print(E)
print(E.shape)
F = np.array([[2],[3],[4]])
print(F)
print(F.shape)
print((E@F).T)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
(5, 3)
[[2]
 [3]
 [4]]
(3, 1)
[[ 9 18 27 36 45]]


### Option 3: Use the Dot Product

In [61]:
print(E.dot(F))

[[ 9]
 [18]
 [27]
 [36]
 [45]]


## Cross-entropy cost function for binary classification.
Is also the negative log-likelihood of the model outputs.

$J = cost \ function \ (error \ function \ or \ objective \ function ) $<br>
$N = samples $<br>
$y = target? $<br>
$Y = short \ form \ of \ P(Y=1 \ | \ X)$

$$J = - \sum_{i = 1}^{N} t_{i}log(y_{i}) + (1 - t_{i})log(1 - y_{i})$$

## Naive Bayes


http://scikit-learn.org/stable/modules/naive_bayes.html

$$P(y|x_{i},...x_{n}) = P(y) \prod_{i=1}^{n} P(x_{i}|y) $$

$$\hat{y} = arg\;  max\; P(y) \prod_{i=1}^{n} P(x_{i}|y)$$
